<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5b0ffb0a49efc',
    'title' => __('Skördetider - Landningssida', 'visithalland'),
    'fields' => array(
        0 => array(
            'key' => 'field_5d075a2c86784',
            'label' => __('Innehåll (ny)', 'visithalland'),
            'name' => 'content_new',
            'type' => 'flexible_content',
            'instructions' => __('När du ändå är i närheten, missa inte dessa fantastiska vyer', 'visithalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'wpml_cf_preferences' => 0,
            'layouts' => array(
                '5b0ffe0b06fa9' => array(
                    'key' => '5b0ffe0b06fa9',
                    'name' => 'post',
                    'label' => __('Post', 'visithalland'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5d075a2d86785',
                            'label' => 'Post',
                            'name' => 'post',
                            'type' => 'post_object',
                            'instructions' => 'Nu börjar det bli matdags, upplev flera halländska favoriter på Ugglarps grönt',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'post_type' => array(
                                0 => 'happening',
                                1 => 'meet_local',
                                2 => 'editor_tip',
                                3 => 'places',
                                4 => 'companies',
                            ),
                            'taxonomy' => '',
                            'allow_null' => 1,
                            'multiple' => 0,
                            'return_format' => 'object',
                            'ui' => 1,
                        ),
                        1 => array(
                            'key' => 'field_5d075a2d86786',
                            'label' => 'Fullbred',
                            'name' => 'fullsize',
                            'type' => 'true_false',
                            'instructions' => 'Ska inlägget sträcka sig över två kolumner?',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'message' => 'Fullbred',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5b0fffae9abec' => array(
                    'key' => '5b0fffae9abec',
                    'name' => 'link',
                    'label' => __('Länk', 'visithalland'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5d075a2d86787',
                            'label' => 'Beskrivning',
                            'name' => 'description',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 2,
                            'new_lines' => '',
                        ),
                        1 => array(
                            'key' => 'field_5d075a2d86788',
                            'label' => 'Titel',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5d075a2d86789',
                            'label' => 'Bild',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        3 => array(
                            'key' => 'field_5d075a2d8678a',
                            'label' => 'Länk',
                            'name' => 'url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        4 => array(
                            'key' => 'field_5d075a2d8678b',
                            'label' => 'Fullbred',
                            'name' => 'fullsize',
                            'type' => 'true_false',
                            'instructions' => 'Ska inlägget sträcka sig över två kolumner?',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'message' => 'Fullbred',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5b21273c3fbf9' => array(
                    'key' => '5b21273c3fbf9',
                    'name' => 'quote',
                    'label' => __('Citat', 'visithalland'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5d075a2d8678c',
                            'label' => 'Citerad',
                            'name' => 'quoted',
                            'type' => 'text',
                            'instructions' => 'Uppge namn på den citerade personen',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5d075a2d8678d',
                            'label' => 'Bild',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => 'Lägg till på den citerade personen',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        2 => array(
                            'key' => 'field_5d075a2d8678e',
                            'label' => 'Citat',
                            'name' => 'quote',
                            'type' => 'textarea',
                            'instructions' => 'Fyll i ett citat',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5b212612659ed' => array(
                    'key' => '5b212612659ed',
                    'name' => 'carousel',
                    'label' => __('Karusell', 'visithalland'),
                    'display' => 'row',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5d075a2d8678f',
                            'label' => 'Innehåll',
                            'name' => 'content',
                            'type' => 'relationship',
                            'instructions' => 'Välj ut innehåll till karusellen',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'post_type' => array(
                                0 => 'happening',
                                1 => 'editor_tip',
                                2 => 'places',
                                3 => 'companies',
                                4 => 'meet_local',
                            ),
                            'taxonomy' => '',
                            'filters' => array(
                                0 => 'search',
                                1 => 'post_type',
                                2 => 'taxonomy',
                            ),
                            'elements' => '',
                            'min' => '',
                            'max' => '',
                            'return_format' => 'object',
                        ),
                        1 => array(
                            'key' => 'field_5d075a2d86790',
                            'label' => 'Sammanfattning',
                            'name' => 'description',
                            'type' => 'text',
                            'instructions' => 'Beskriv innehållet i karusellen',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'wpml_cf_preferences' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'button_label' => __('Lägg till innehåll', 'visithalland'),
            'min' => '',
            'max' => '',
        ),
        1 => array(
            'key' => 'field_5b0ffb9f0501c',
            'label' => __('Veckor', 'visithalland'),
            'name' => 'timeline',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'wpml_cf_preferences' => 0,
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => __('Lägg till vecka', 'visithalland'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5b0ffe0355149',
                    'label' => __('Innehåll', 'visithalland'),
                    'name' => 'content',
                    'type' => 'flexible_content',
                    'instructions' => __('När du ändå är i närheten, missa inte dessa fantastiska vyer', 'visithalland'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        '5b0ffe0b06fa9' => array(
                            'key' => '5b0ffe0b06fa9',
                            'name' => 'post',
                            'label' => __('Post', 'visithalland'),
                            'display' => 'row',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5b0ffe5e41b92',
                                    'label' => 'Post',
                                    'name' => 'post',
                                    'type' => 'post_object',
                                    'instructions' => 'Nu börjar det bli matdags, upplev flera halländska favoriter på Ugglarps grönt',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'companies',
                                        1 => 'happening',
                                        2 => 'meet_local',
                                        3 => 'trip',
                                        4 => 'editor_tip',
                                        5 => 'places',
                                    ),
                                    'taxonomy' => array(
                                    ),
                                    'allow_null' => 1,
                                    'multiple' => 0,
                                    'return_format' => 'object',
                                    'ui' => 1,
                                ),
                                1 => array(
                                    'key' => 'field_5b192f64bebdd',
                                    'label' => 'Fullbred',
                                    'name' => 'fullsize',
                                    'type' => 'true_false',
                                    'instructions' => 'Ska inlägget sträcka sig över två kolumner?',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => 'Fullbred',
                                    'default_value' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '5b0fffae9abec' => array(
                            'key' => '5b0fffae9abec',
                            'name' => 'link',
                            'label' => __('Länk', 'visithalland'),
                            'display' => 'row',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5b1936c6a4607',
                                    'label' => 'Beskrivning',
                                    'name' => 'description',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => 2,
                                    'new_lines' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5b1936bea4606',
                                    'label' => 'Titel',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                2 => array(
                                    'key' => 'field_5b1936d9a4608',
                                    'label' => 'Bild',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                3 => array(
                                    'key' => 'field_5b1936e9a4609',
                                    'label' => 'Länk',
                                    'name' => 'url',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                ),
                                4 => array(
                                    'key' => 'field_5b192fd0bebde',
                                    'label' => 'Fullbred',
                                    'name' => 'fullsize',
                                    'type' => 'true_false',
                                    'instructions' => 'Ska inlägget sträcka sig över två kolumner?',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => 'Fullbred',
                                    'default_value' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '5b21273c3fbf9' => array(
                            'key' => '5b21273c3fbf9',
                            'name' => 'quote',
                            'label' => __('Citat', 'visithalland'),
                            'display' => 'row',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5b2127633fbfb',
                                    'label' => 'Citerad',
                                    'name' => 'quoted',
                                    'type' => 'text',
                                    'instructions' => 'Uppge namn på den citerade personen',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5b2127ba3fbfc',
                                    'label' => 'Bild',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => 'Lägg till på den citerade personen',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                2 => array(
                                    'key' => 'field_5b2127473fbfa',
                                    'label' => 'Citat',
                                    'name' => 'quote',
                                    'type' => 'textarea',
                                    'instructions' => 'Fyll i ett citat',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '5b212612659ed' => array(
                            'key' => '5b212612659ed',
                            'name' => 'carousel',
                            'label' => __('Karusell', 'visithalland'),
                            'display' => 'row',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5b212648659ef',
                                    'label' => 'Innehåll',
                                    'name' => 'content',
                                    'type' => 'relationship',
                                    'instructions' => 'Välj ut innehåll till karusellen',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'happening',
                                        1 => 'editor_tip',
                                        2 => 'companies',
                                        3 => 'places',
                                        4 => 'trip',
                                    ),
                                    'taxonomy' => array(
                                    ),
                                    'filters' => array(
                                        0 => 'search',
                                        1 => 'post_type',
                                        2 => 'taxonomy',
                                    ),
                                    'elements' => '',
                                    'min' => '',
                                    'max' => '',
                                    'return_format' => 'object',
                                ),
                                1 => array(
                                    'key' => 'field_5b21262b659ee',
                                    'label' => 'Sammanfattning',
                                    'name' => 'description',
                                    'type' => 'text',
                                    'instructions' => 'Beskriv innehållet i karusellen',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => __('Lägg till innehåll', 'visithalland'),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'views/st-template-landing.blade.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
    ),
    'active' => true,
    'description' => 'Här finns all information kopplat till Skördetider',
));
}