<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5b0ffb0a49efc',
    'title' => __('Weekend', 'visithalland'),
    'fields' => array(
        0 => array(
            'key' => 'field_5b0ffb9f0501c',
            'label' => __('Tidslinje', 'visithalland'),
            'name' => 'timeline',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => '',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5b0ffd9033240',
                    'label' => __('Startdatum', 'visithalland'),
                    'name' => 'date_start',
                    'type' => 'date_picker',
                    'instructions' => __('Välj ett startdatum', 'visithalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'd/m/Y',
                    'return_format' => 'd/m/Y',
                    'first_day' => 1,
                ),
                1 => array(
                    'key' => 'field_5b1910f01f097',
                    'label' => __('Slutdatum', 'visithalland'),
                    'name' => 'date_end',
                    'type' => 'date_picker',
                    'instructions' => __('Välj ett slutdatum', 'visithalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'd/m/Y',
                    'return_format' => 'd/m/Y',
                    'first_day' => 1,
                ),
                2 => array(
                    'key' => 'field_5b0ffe0355149',
                    'label' => __('Innehåll', 'visithalland'),
                    'name' => 'content',
                    'type' => 'flexible_content',
                    'instructions' => __('När du ändå är i närheten, missa inte dessa fantastiska vyer', 'visithalland'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        '5b0ffe0b06fa9' => array(
                            'key' => '5b0ffe0b06fa9',
                            'name' => 'post',
                            'label' => __('Post', 'visithalland'),
                            'display' => 'row',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5b0ffe5e41b92',
                                    'label' => 'Post',
                                    'name' => 'post',
                                    'type' => 'post_object',
                                    'instructions' => 'Nu börjar det bli matdags, upplev flera halländska favoriter på Ugglarps grönt',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                    ),
                                    'taxonomy' => array(
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'return_format' => 'object',
                                    'ui' => 1,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '5b0fffae9abec' => array(
                            'key' => '5b0fffae9abec',
                            'name' => 'link',
                            'label' => __('Länk', 'visithalland'),
                            'display' => 'row',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5b18e66ce782c',
                                    'label' => 'Länk',
                                    'name' => 'link',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'block',
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_5b18e6a2e782d',
                                            'label' => 'Titel',
                                            'name' => 'title',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        1 => array(
                                            'key' => 'field_5b18e6d7e782e',
                                            'label' => 'Beskrivning',
                                            'name' => 'description',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => -12,
                                            'new_lines' => '',
                                        ),
                                        2 => array(
                                            'key' => 'field_5b18e752e782f',
                                            'label' => 'Bild',
                                            'name' => 'image',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        3 => array(
                                            'key' => 'field_5b18e761e7830',
                                            'label' => 'Länk',
                                            'name' => 'link',
                                            'type' => 'url',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => __('Lägg till rad', 'visithalland'),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'weekend',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
));
}