<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5acb39a64e81f',
    'title' => 'Kampanj',
    'fields' => array(
        0 => array(
            'key' => 'field_5acb39aadaa4f',
            'label' => __('Kampanjväljare', 'visithalland'),
            'name' => 'campaign_toggle',
            'type' => 'true_false',
            'instructions' => __('Klicka i den här om du vill aktivera kampanjläget', 'visithalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Visa kampanj', 'visithalland'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        1 => array(
            'key' => 'field_5acb4ba928783',
            'label' => __('Kampanj', 'visithalland'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5acb39aadaa4f',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        2 => array(
            'key' => 'field_5acb39e6f1116',
            'label' => __('Kampanjbild', 'visithalland'),
            'name' => 'campaign_img',
            'type' => 'image',
            'instructions' => __('Välj bild för kampanjen', 'visithalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        3 => array(
            'key' => 'field_5acb39fef1117',
            'label' => __('Kampantitel', 'visithalland'),
            'name' => 'campaign_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        4 => array(
            'key' => 'field_5acb4bda28784',
            'label' => __('Kampanjutdrag', 'visithalland'),
            'name' => 'campaign_excerpt',
            'type' => 'text',
            'instructions' => __('Fyll i utdrag för kampanjen', 'visithalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => __('Skriv här', 'visithalland'),
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        5 => array(
            'key' => 'field_5acb4bf328785',
            'label' => __('Internlänk', 'visithalland'),
            'name' => 'internal_link',
            'type' => 'link',
            'instructions' => __('Välj intern länk till för kampanjen', 'visithalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
        ),
        6 => array(
            'key' => 'field_5acb4c0728786',
            'label' => __('Extern länk', 'visithalland'),
            'name' => 'external_link',
            'type' => 'url',
            'instructions' => __('Fyll i URL till extern site', 'visithalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Fält som används för att visa tillfälliga kampanjer',
));
}