if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5acb39a64e81f',
	'title' => 'Kampanj',
	'fields' => array(
		array(
			'key' => 'field_5acb39aadaa4f',
			'label' => 'Kampanjväljare',
			'name' => 'campaign_toggle',
			'type' => 'true_false',
			'instructions' => 'Klicka i den här om du vill aktivera kampanjläget',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Visa kampanj',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5acb4ba928783',
			'label' => 'Kampanj',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5acb39aadaa4f',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5acb39e6f1116',
			'label' => 'Kampanjbild',
			'name' => 'campaign_img',
			'type' => 'image',
			'instructions' => 'Välj bild för kampanjen',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5acb39fef1117',
			'label' => 'Kampantitel',
			'name' => 'campaign_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5acb4bda28784',
			'label' => 'Kampanjutdrag',
			'name' => 'campaign_excerpt',
			'type' => 'text',
			'instructions' => 'Fyll i utdrag för kampanjen',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Skriv här',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5acb4bf328785',
			'label' => 'Internlänk',
			'name' => 'internal_link',
			'type' => 'link',
			'instructions' => 'Välj intern länk till för kampanjen',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_5acb4c0728786',
			'label' => 'Extern länk',
			'name' => 'external_link',
			'type' => 'url',
			'instructions' => 'Fyll i URL till extern site',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Fält som används för att visa tillfälliga kampanjer',
));

endif;