if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_58a6da2dafd35',
	'title' => 'Koncept',
	'fields' => array(
		array(
			'key' => 'field_58ac64c532084',
			'label' => 'Utdrag',
			'name' => 'excerpt',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
		),
		array(
			'key' => 'field_58ac1e314914e',
			'label' => 'Omslagsbild',
			'name' => 'cover_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5acb577ffecfd',
			'label' => 'Utvalda artiklar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58d2a4f73acee',
			'label' => 'Utvalda artiklar',
			'name' => 'featured',
			'type' => 'relationship',
			'instructions' => 'Lägg till utvalda artiklar som visas högst upp på varje koncept',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'meet_local',
				1 => 'editor_tip',
				2 => 'companies',
				3 => 'trip',
				4 => 'happening',
				5 => 'places',
			),
			'taxonomy' => array(
			),
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'elements' => array(
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array(
			'key' => 'field_5acb571b95e17',
			'label' => 'Utvald artikel',
			'name' => 'featured_article',
			'type' => 'post_object',
			'instructions' => 'Lägg till utvald artikel för det valda konceptet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'meet_local',
				1 => 'editor_tip',
				2 => 'happening',
				3 => 'places',
				4 => 'companies',
				5 => 'trip',
			),
			'taxonomy' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array(
			'key' => 'field_5acb5792fecfe',
			'label' => 'Metainformation',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5acb56ed95e16',
			'label' => 'Klassnamn',
			'name' => 'class_name',
			'type' => 'text',
			'instructions' => 'Fyll i klassnamnet för att visa rätt ikon och färg för varje koncept',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'taxonomy_concept',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Här väljer vi ut vilka artiklar som ska synas högst upp samt ingress och bakgrundsbild för varje koncept',
));

endif;